modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
[[mods]] #mandatory
modId = "openseasons" #mandatory
version = "${file.jarVersion}" #mandatory
# A display name for the mod
displayName = "Open Seasons" #mandatory
displayURL = "awagga"
logoFile = ""
credits = "WIP"
authors = "Noobulus"
description = '''WIP'''
[[dependencies.openseasons]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[39.0.73,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.openseasons]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"